### ISSUE TITLE
Error while backup using 'None' compression type

### ISSUE THREAD

**Issue by Adekabang** [Performave/convoy#87]
### Current Behavior

When do backup on VM using this parameter
`Compression Type`: `None`
`Mode`: `Snapshot`,`Suspend`, or `Kill`

Got this error

Error Message:
```
Parameter verification failed. HTTP request returned status code 400: {"data":null,"errors":{"compress":"type check ('string') failed - got JSON::PP::Boolean"}} #0 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/Response.php(289): Illuminate\Http\Client\Response->toException() #1 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(911): Illuminate\Http\Client\Response->throw(Object(Closure)) #2 /var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\Http\Client\PendingRequest->Illuminate\Http\Client\{closure}(Object(Illuminate\Http\Client\Response)) #3 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(894): tap(Object(Illuminate\Http\Client\Response), Object(Closure)) #4 /var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\Http\Client\PendingRequest->Illuminate\Http\Client\{closure}(1) #5 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(892): retry(0, Object(Closure), 100, Object(Closure)) #6 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(798): Illuminate\Http\Client\PendingRequest->send('POST', 'api2/json/nodes...', Array) #7 /var/www/app/Repositories/Proxmox/Server/ProxmoxBackupRepository.php(49): Illuminate\Http\Client\PendingRequest->post('/api2/json/node...', Array) #8 /var/www/app/Services/Backups/BackupCreationService.php(68): Convoy\Repositories\Proxmox\Server\ProxmoxBackupRepository->backup(Object(Convoy\Enums\Server\BackupMode), Object(Convoy\Enums\Server\BackupCompressionType)) #9 /var/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): Convoy\Services\Backups\BackupCreationService->Convoy\Services\Backups\{closure}(Object(Illuminate\Database\MySqlConnection)) #10 /var/www/app/Services/Backups/BackupCreationService.php(59): Illuminate\Database\Connection->transaction(Object(Closure)) #11 /var/www/app/Http/Controllers/Client/Servers/BackupController.php(49): Convoy\Services\Backups\BackupCreationService->create(Object(Convoy\Models\Server), 'efwasc', Object(Convoy\Enums\Server\BackupMode), Object(Convoy\Enums\Server\BackupCompressionType), false) #12 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Convoy\Http\Controllers\Client\Servers\BackupController->store(Object(Convoy\Http\Requests\Client\Servers\Backups\StoreBackupRequest), Object(Convoy\Models\Server)) #13 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('store', Array) #14 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Convoy\Http\Controllers\Client\Servers\BackupController), 'store') #15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController() #16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Routing\Route->run() #17 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #18 /var/www/app/Http/Middleware/Client/Server/AuthenticateServerAccess.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #19 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Convoy\Http\Middleware\Client\Server\AuthenticateServerAccess->handle(Object(Illuminate\Http\Request), Object(Closure)) #20 /var/www/app/Http/Middleware/Activity/ServerSubject.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Convoy\Http\Middleware\Activity\ServerSubject->handle(Object(Illuminate\Http\Request), Object(Closure)) #22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #23 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #24 /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #25 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure)) #26 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #28 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #30 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #31 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure)) #32 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #33 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #35 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #37 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #38 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #39 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #40 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #41 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #42 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #44 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #45 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #46 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure)) #47 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #48 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure)) #50 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure)) #52 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure)) #54 /var/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure)) #56 /var/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #57 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure)) #58 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #59 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #60 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #61 /var/www/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #62 {main}
```

### Expected Behavior

No Error and create backup in none compression

### Steps to Reproduce

Do backup on VM using this parameter
`Compression Type`: `None`
`Mode`: `Snapshot`,`Suspend`, or `Kill`

### Screenshots

![image](https://github.com/ConvoyPanel/panel/assets/42745054/611c63ce-4c9a-4b70-99bb-263e77076d13)

### Proxmox OS Version

8.1.4

### Operating System

macOS 13.6.5 (ventura)

### Browser

Chrome

### Panel Version

version 4.2.2-rc.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ericwang401** [comment]
Resolved in https://github.com/ConvoyPanel/panel/commit/c780ca02181abe3d2a4851f53819c80b4d541e37
